### ISSUE TITLE
Taxonomic tree

### ISSUE THREAD

**Issue by diegozea** [EcoJulia/NCBITaxonomy.jl#32]
Hi!

First, thank you very much for this package! It has been handy for me. 

I think that it would be great to have an integration with [Phylo.jl](https://github.com/EcoJulia/Phylo.jl) to easily get the common taxonomic tree for a set of taxa as in the [NCBI site](https://www.ncbi.nlm.nih.gov/guide/howto/gen-com-tree/). That could be really useful for visualization and exploration.

Ideally, this can be a single function, similar to `lineage` and most probably depending on that, that also accepts `stop_at`, but that takes a list/set of `NCBITaxon`s. For example:

~~~ julia
using NCBITaxonomy

common_tree([ncbi"Bos taurus", ncbi"Mus musculus", ncbi"Homo sapiens"], stop_at=ncbi"Mammalia")
~~~

Best regards,

**Comment by tpoisot** [comment]
Thank you! It's one of the planned features. I think @richardreeve has done the work on Phylo.jl to make it relatively easy to build, and that's definitely on my list.

**Comment by tpoisot** [comment]
I have made a *documentation page* with an example - I think it's a good idea, but I would like to think a bit about the best way to express it.

It can be something like

```julia
RootedTree(t::Vector{NCBITaxon}) # Or other types from Phylo
```

Or it can be a convert function. I'm unsure about the API. @richardreeve and @mkborregaard do you have preferences?

This will be a post `v0.1.0` addition anyways, since I have modified the package a bit to make it faster.

**Comment by tpoisot** [comment]
@diegozea here is the use-case with `Phylo.jl` -- I'm happy to keep thinking about how we can make the process efficient (and this will likely involve some performance improvements in `lineage`, which is not *super* fast now).

**Comment by diegozea** [comment]
Thanks! That example is really useful :)

One thing; do you know why the tips are not being shown? I believe it is a problem with the plot recipe, as `getleafnames(tree)` works perfectly in that example.

**Comment by mkborregaard** [comment]
> do you know why the tips are not being shown? 

There seems to be a bug in the plot recipe. It must be due to changes in Plots, as this did work earlier. Could you open a Phylo issue for it?
