### ISSUE TITLE
Citing NCBITaxonomy.jl

### ISSUE THREAD

**Issue by Rekyt** [EcoJulia/NCBITaxonomy.jl#38]
Hey NCBITaxonomy.jl maintainers 👋 (@tpoisot mostly, I suppose? :))
With a group of people we're currently working on reviewing tools for taxonomic name harmonization for ecologists.
With mostly focused on R packages as R is the most used programming language by ecologists.

However we would like to have a section about tools that exist in other languages. As such we'd like to mention `NCBITaxonomy.jl`, but I'm not familiar with citation practice in Julia modules
How should I cite the module? Do you know any other modules that may be relevant for taxonomic name harmonization?

Thanks :)

**Comment by tpoisot** [comment]
Nice! I can definitely link this to Zenodo and this will give a DOI. There's a also a python module, which I need to dig up.

**Comment by tpoisot** [comment]
https://zenodo.org/record/4632349 is the Zenodo record, it has citation info in the sidebar ^^ !

**Comment by Rekyt** [comment]
Awesome! Thank you for the blazing fast answer and citation!

**Comment by tpoisot** [comment]
There's also https://joss.theoj.org/papers/10.21105/joss.02872 which describes our GBIF API wrapper, a [Rust](https://crates.io/crates/ncbitaxonomy) wrapper on NCBI taxonomy, and a few python packages.
